export const GOTRAS = [
    { en: 'Angirasa', kn: 'ಆಂಗೀರಸ' },
    { en: 'Atri', kn: 'ಅತ್ರಿ' },
    { en: 'Bharadvaja', kn: 'ಭಾರದ್ವಾಜ' },
    { en: 'Bhrigu', kn: 'ಭೃಗು' },
    { en: 'Gautama', kn: 'ಗೌತಮ' },
    { en: 'Kashyapa', kn: 'ಕಾಶ್ಯಪ' },
    { en: 'Vasistha', kn: 'ವಸಿಷ್ಠ' },
    { en: 'Vishvamitra', kn: 'ವಿಶ್ವಾಮಿತ್ರ' },
    { en: 'Agastya', kn: 'ಅಗಸ್ತ್ಯ' },
    { en: 'Jamadagni', kn: 'ಜಮದಗ್ನಿ' },
    { en: 'Kaundinya', kn: 'ಕೌಂಡಿನ್ಯ' },
    { en: 'Shandilya', kn: 'ಶಾಂಡಿಲ್ಯ' },
    { en: 'Kutsa', kn: 'ಕುತ್ಸ' },
    { en: 'Harita', kn: 'ಹರಿತ' },
    { en: 'Maudgalya', kn: 'ಮೌದ್ಗಲ್ಯ' },
    { en: 'Srivatsa', kn: 'ಶ್ರೀವತ್ಸ' },
    { en: 'Vatsa', kn: 'ವತ್ಸ' },
    { en: 'Lohita', kn: 'ಲೋಹಿತ' },
];

export const NAKSHATRAS = [
    { en: 'Ashvini', kn: 'ಅಶ್ವಿನಿ' },
    { en: 'Bharani', kn: 'ಭರಣಿ' },
    { en: 'Krittika', kn: 'ಕೃತ್ತಿಕಾ' },
    { en: 'Rohini', kn: 'ರೋಹಿಣಿ' },
    { en: 'Mrigashirsha', kn: 'ಮೃಗಶಿರ' },
    { en: 'Ardra', kn: 'ಆರ್ದ್ರಾ' },
    { en: 'Punarvasu', kn: 'ಪುನರ್ವಸು' },
    { en: 'Pushya', kn: 'ಪುಷ್ಯ' },
    { en: 'Ashlesha', kn: 'ಆಶ್ಲೇಷಾ' },
    { en: 'Magha', kn: 'ಮಖಾ' },
    { en: 'Purva Phalguni', kn: 'ಪೂರ್ವ ಫಾಲ್ಗುಣಿ' },
    { en: 'Uttara Phalguni', kn: 'ಉತ್ತರ ಫಾಲ್ಗುಣಿ' },
    { en: 'Hasta', kn: 'ಹಸ್ತ' },
    { en: 'Chitra', kn: 'ಚಿತ್ತ' },
    { en: 'Svati', kn: 'ಸ್ವಾತಿ' },
    { en: 'Vishakha', kn: 'ವಿಶಾಖಾ' },
    { en: 'Anuradha', kn: 'ಅನುರಾಧಾ' },
    { en: 'Jyeshtha', kn: 'ಜ್ಯೇಷ್ಠ' },
    { en: 'Mula', kn: 'ಮೂಲ' },
    { en: 'Purva Ashadha', kn: 'ಪೂರ್ವಾಷಾಢ' },
    { en: 'Uttara Ashadha', kn: 'ಉತ್ತರಾಷಾಢ' },
    { en: 'Shravana', kn: 'ಶ್ರವಣ' },
    { en: 'Dhanishtha', kn: 'ಧನಿಷ್ಠಾ' },
    { en: 'Shatabhisha', kn: 'ಶತಭಿಷಾ' },
    { en: 'Purva Bhadrapada', kn: 'ಪೂರ್ವ ಭಾದ್ರಪದ' },
    { en: 'Uttara Bhadrapada', kn: 'ಉತ್ತರ ಭಾದ್ರಪದ' },
    { en: 'Revati', kn: 'ರೇವತಿ' },
];
