"""initial_schema

Revision ID: 79816d05d0ab
Revises: 
Create Date: 2026-06-25 19:12:07.436136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79816d05d0ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Gotra')
    op.drop_table('PS_Receipts')
    op.drop_table('Payment')
    op.drop_table('Item_Old')
    op.drop_table('SyncConfig')
    op.drop_table('Security')
    op.drop_table('FinancialYear_Mst')
    op.drop_table('PL_Seva')
    op.drop_table('Nakshatra_Raashi')
    op.add_column('BankTransaction', sa.Column('Status', sa.String(), nullable=True))
    op.alter_column('Customer', 'ID1',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Customer', 'ID',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Customer', 'Name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Customer', 'Sgotra',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Customer', 'SNakshatra',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Customer', 'Address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Customer', 'City',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Customer', 'Phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Customer', 'WhatsApp_Phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Customer', 'Email_ID',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Customer', 'Google_Maps_Location',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_Customer_ID1'), 'Customer', ['ID1'], unique=False)
    op.drop_column('Customer', 'Creditor')
    op.drop_column('Customer', 'Debitor')
    op.add_column('Donation', sa.Column('PaymentMode', sa.String(), nullable=True))
    op.add_column('Donation', sa.Column('PaymentReference', sa.String(), nullable=True))
    op.add_column('Donation', sa.Column('PaymentDetails', sa.JSON(), nullable=True))
    op.drop_index(op.f('idx_event_composition_parent'), table_name='EventComposition')
    op.alter_column('InventoryCategory', 'ForType',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'asset'"))
    op.alter_column('InventoryItem', 'ItemType',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'asset'"))
    op.alter_column('InventoryItem', 'UOM',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Nos'"))
    op.alter_column('InventoryItem', 'GSTRate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('InventoryItem', 'HSNCode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('InventoryItem', 'AcquisitionMode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'purchase'"))
    op.add_column('Invoice_Dtl', sa.Column('rowid', sa.Integer(), nullable=False))
    op.alter_column('Invoice_Dtl', 'InvoiceNo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Dtl', 'ItemCode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Dtl', 'Basic',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('Invoice_Dtl', 'TPQty',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('Invoice_Dtl', 'Amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.add_column('Invoice_Hdr', sa.Column('rowid', sa.Integer(), nullable=False))
    op.add_column('Invoice_Hdr', sa.Column('ItemCode', sa.String(), nullable=True))
    op.alter_column('Invoice_Hdr', 'InvoiceNo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'InvoiceDate',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'ID',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'PO_Date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'EntryTime',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'Remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'ItemRateTotal',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'TotalTPQty',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'GrandTotal',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'PaymentCode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'ChqNo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'Payment_Mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'VoucherNo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'CustomerCode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'TotalAmount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'Payment_Reference',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('Invoice_Hdr', 'Adustment2')
    op.drop_column('Invoice_Hdr', 'Adustment1')
    op.alter_column('Item', 'ItemCode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('Item', 'Description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('Item', 'Basic',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('Item', 'TPQty',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_Item_ItemCode'), 'Item', ['ItemCode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Item_ItemCode'), table_name='Item')
    op.alter_column('Item', 'TPQty',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('Item', 'Basic',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('Item', 'Description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Item', 'ItemCode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('Invoice_Hdr', sa.Column('Adustment1', sa.INTEGER(), nullable=True))
    op.add_column('Invoice_Hdr', sa.Column('Adustment2', sa.INTEGER(), nullable=True))
    op.alter_column('Invoice_Hdr', 'Payment_Reference',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'TotalAmount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'CustomerCode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'VoucherNo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'Payment_Mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'ChqNo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'PaymentCode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'GrandTotal',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'TotalTPQty',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'ItemRateTotal',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'Remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'EntryTime',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'PO_Date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'ID',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'InvoiceDate',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Invoice_Hdr', 'InvoiceNo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('Invoice_Hdr', 'ItemCode')
    op.drop_column('Invoice_Hdr', 'rowid')
    op.alter_column('Invoice_Dtl', 'Amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('Invoice_Dtl', 'TPQty',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('Invoice_Dtl', 'Basic',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('Invoice_Dtl', 'ItemCode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Invoice_Dtl', 'InvoiceNo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('Invoice_Dtl', 'rowid')
    op.alter_column('InventoryItem', 'AcquisitionMode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'purchase'"))
    op.alter_column('InventoryItem', 'HSNCode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('InventoryItem', 'GSTRate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('InventoryItem', 'UOM',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Nos'"))
    op.alter_column('InventoryItem', 'ItemType',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'asset'"))
    op.alter_column('InventoryCategory', 'ForType',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'asset'"))
    op.create_index(op.f('idx_event_composition_parent'), 'EventComposition', ['ParentEventCode'], unique=False)
    op.drop_column('Donation', 'PaymentDetails')
    op.drop_column('Donation', 'PaymentReference')
    op.drop_column('Donation', 'PaymentMode')
    op.add_column('Customer', sa.Column('Debitor', sa.TEXT(), nullable=True))
    op.add_column('Customer', sa.Column('Creditor', sa.REAL(), nullable=True))
    op.drop_index(op.f('ix_Customer_ID1'), table_name='Customer')
    op.alter_column('Customer', 'Google_Maps_Location',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Customer', 'Email_ID',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Customer', 'WhatsApp_Phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Customer', 'Phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Customer', 'City',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Customer', 'Address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Customer', 'SNakshatra',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Customer', 'Sgotra',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Customer', 'Name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Customer', 'ID',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('Customer', 'ID1',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('BankTransaction', 'Status')
    op.create_table('Nakshatra_Raashi',
    sa.Column('SNakshatra', sa.TEXT(), nullable=True),
    sa.Column('SRaashi', sa.TEXT(), nullable=True)
    )
    op.create_table('PL_Seva',
    sa.Column('ID_PL', sa.INTEGER(), nullable=True),
    sa.Column('Seva', sa.TEXT(), nullable=True),
    sa.Column('PL_Rate', sa.INTEGER(), nullable=True)
    )
    op.create_table('FinancialYear_Mst',
    sa.Column('Fycode', sa.TEXT(), nullable=True),
    sa.Column('Description', sa.TEXT(), nullable=True),
    sa.Column('StartDate', sa.TEXT(), nullable=True),
    sa.Column('EndDate', sa.TEXT(), nullable=True),
    sa.Column('PrevFycode', sa.REAL(), nullable=True)
    )
    op.create_table('Security',
    sa.Column('User_Id', sa.TEXT(), nullable=True),
    sa.Column('Pass_Word', sa.TEXT(), nullable=True)
    )
    op.create_table('SyncConfig',
    sa.Column('Key', sa.TEXT(), nullable=True),
    sa.Column('Value', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('Key')
    )
    op.create_table('Item_Old',
    sa.Column('ItemCode', sa.TEXT(), nullable=True),
    sa.Column('Description', sa.TEXT(), nullable=True),
    sa.Column('Basic', sa.INTEGER(), nullable=True),
    sa.Column('TPQty', sa.INTEGER(), nullable=True)
    )
    op.create_table('Payment',
    sa.Column('PaymentCode', sa.TEXT(), nullable=True)
    )
    op.create_table('PS_Receipts',
    sa.Column('PS_ID', sa.INTEGER(), nullable=True),
    sa.Column('PS_RDate', sa.TEXT(), nullable=True),
    sa.Column('PS_SDate', sa.TEXT(), nullable=True),
    sa.Column('PS_Sevakartha', sa.TEXT(), nullable=True),
    sa.Column('SGotra', sa.TEXT(), nullable=True),
    sa.Column('SNakshatra', sa.TEXT(), nullable=True),
    sa.Column('SRaashi', sa.REAL(), nullable=True),
    sa.Column('PS_Seva', sa.TEXT(), nullable=True),
    sa.Column('PS_Qty', sa.INTEGER(), nullable=True),
    sa.Column('PS_Rate', sa.INTEGER(), nullable=True),
    sa.Column('PS_Amount', sa.REAL(), nullable=True),
    sa.Column('PS_Amt_Words', sa.TEXT(), nullable=True)
    )
    op.create_table('Gotra',
    sa.Column('GotraCode', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
